### ISSUE TITLE
Disable/enable features on demand

### ISSUE THREAD

**Issue by jcfaracco** [Eve-ning/glcm-cupy#20]
If you calculate GLCM today, it returns all the 6 features implemented.

Most researchers or developers don't need all features calculated and if you have a huge size of images to calculate it could mean a huge memory consumption.

In my case I have a dataset of 2 GB and if I multiply by 6 (number of features), my code needs 8 GB at least to run. (Ok, I know... there are several workarounds for it 😃, but I'm imagining a real time scenario).

This feature request would be interesting because we cal also compare the speedup GLCM calculation with scikit image for each props separately.

**Comment by Eve-ning** [comment]
I'll see if I have time to get to this this weekend

**Comment by jcfaracco** [comment]
@Eve-ning I created that request because we could implement a portable API with scikit image where you generate the GLCM and get each feature calling props method. But it is better to calculate specific features instead of all and then request it from a huge data.

**Comment by jcfaracco** [comment]
Honestly, I have tried to implement, but it is not easy. I would not like to mess your code.

**Comment by Eve-ning** [comment]
would love to work with scikit-image to implement this, though I wonder how easy it'll be to integrate it

**Comment by jcfaracco** [comment]
Thank you very much @Eve-ning 
You helped me a lot!

**Comment by Eve-ning** [comment]
> Thank you very much @Eve-ning You helped me a lot!

My pleasure, thanks for raising this 👍
