### ISSUE TITLE
Reduction of original image size

### ISSUE THREAD

**Issue by APPGC** [Eve-ning/glcm-cupy#31]
Hello, really great work in implementing this. One question...:

I understand the image shrinks because of the effect of the sliding window on the edges. Wouldn't there be a way around that by padding the original image on its outside dimensions with artificial values (a number not used in the grayscale binning range - let's say 0, while the scale of the image would be (1-16), instead of (0-15). GLCMs rows and columns with 0 would then have to be removed before haralick features calculations.

**Comment by Eve-ning** [comment]
sounds good, I'll see when I can get to it

**Comment by APPGC** [comment]
Excellent, thanks for the quick reply! A side question to this is how, using your code, to filter out background values if there is background in the image (not a fully filled rectangular image). I have something that works well at the moment, but I am looking at improving computational speed that's why I am looking at your implementation. At the moment with scikit-image and custom sliding window, I simply remove the rows corresponding to the background values in the GLCM. That would be in Kernel1 for your code, right?

**Comment by Eve-ning** [comment]
not sure what you mean by that, Kernel 1 calculates GLCM Variance

Kernel 0 calculates
- homogeneity
- contrast
- asm
- mean

Kernel 2 calculates correlation

also I'm not too sure about using GLCM to filter our backgrounds, haven't read up on that use-case, perhaps GLCM Variance does that well?

**Comment by APPGC** [comment]
Ah sorry I was completely wrong then with Kernel1. 

GLCM variance would possibly work for the pixels far away from the contour edges, but won't work for the pixels bordering the contour. The principle for the contours and for the image padding is the exact same: You want to remove in the GLCM the row and the column corresponding to relationships between the pixel with no data - and the other pixels, so if that is 0 for no data (or background data), these are first row and first column of the GLC matrix (binsize*binsize). I did not get yet where the GLC matrix is calculated before being passed to calculate GLCM features in your code...

**Comment by Eve-ning** [comment]
> I did not get yet where the GLC matrix is calculated before being passed to calculate GLCM features in your code...

It's here, it's a Python string converted to CUDA
https://github.com/Eve-ning/glcm-cupy/blob/master/glcm_cupy/kernel.py#L165-L176

A for loop to `atomicAdd` (add) to `g`, which is a pointer to a float array

----

It is being called by
https://github.com/Eve-ning/glcm-cupy/blob/master/glcm_cupy/glcm_base.py#L303-L315

This populates the GLCM `cp.ndarray` provided before calculating each feature

**Comment by APPGC** [comment]
Thanks! That is lots clearer now but given I never used cupy, that's a steep learning curve...

Another question if I may: are you defining the distance indirectly via the radius? i.e. in theory, we can have a distance of as an example d =  1, and a window width of 10. Is that possible to implement distance and window size independently in your existing implementation or is the distance hardwired to the window size?

**Comment by Eve-ning** [comment]
I assume you mean distance as in step-size (similar to stride in convolution)
Currently it steps by 1 in all 8 directions. (diagonal counts as 1)
But yes, it's definitely possible to have them independently implemented, will have to figure out how to do that in CuPy though

**Comment by APPGC** [comment]
Thanks: That is correct. That's a secondary thing though, for me the possibility of enlarging the image with padding, and contouring within the image by removing relations between non-valid values and valid values is the critical aspect I'd need to compare your retrieval with the one I am currently using.

**Comment by Eve-ning** [comment]
Will add examples on how to achieve padding in another PR, but for now it's implemented in `master`

**Comment by APPGC** [comment]
Excellent, fantastic! I'll be testing soon and keeping you posted.

**Comment by Eve-ning** [comment]
Forgot to update, closed by #44

**Comment by Eve-ning** [comment]
another update, you can see the use-case here
https://eve-ning.github.io/glcm-cupy/examples/image_padding.html
