### ISSUE TITLE
IndexError: tuple index out of range in glcm_cupy/glcm/glcm.py

### ISSUE THREAD

**Issue by binit9** [Eve-ning/glcm-cupy#9]
Hello, 

 I am facing this error. Error details and my usage are shown below:

   

>  g = GLCM(
>   File "/anaconda/envs/cucim/lib/python3.9/site-packages/glcm_cupy/glcm_base.py", line 107, in run
>     self.progress = tqdm(total=self.glcm_cells(im),
>   File "/anaconda/envs/cucim/lib/python3.9/site-packages/glcm_cupy/glcm/glcm.py", line 82, in glcm_cells
>     return np.prod(self.glcm_shape(im[..., 0])) * \
>   File "/anaconda/envs/cucim/lib/python3.9/site-packages/glcm_cupy/glcm/glcm.py", line 90, in glcm_shape
>     im_chn.shape[1] - 2 * self.step_size - 2 * self.radius)
> IndexError: tuple index out of range

```
def get_glcm_gpu(patch):
    ar = np.asarray(patch)
    # g = GLCM(directions=(Direction.EAST, Direction.SOUTH_EAST, Direction.SOUTH, 
    #             Direction.SOUTH_WEST), bin_from=256, bin_to=16).run(patch)
    g = GLCM(
            directions=(Direction.EAST, Direction.SOUTH_EAST),
            bin_from=256, bin_to=16).run(ar)

    return g
```
**patch** is nothing but a grayscale image of size (50, 50). Please help.

**Comment by Eve-ning** [comment]
yeap you're right on that error, please do convert grayscale images (1 channel images) to 3d by adding another axis.

I will improve the error message

```py
ar = np.random.randint(0, 256, (50, 50), dtype=np.uint8)
g = GLCM(
    directions=(Direction.EAST, Direction.SOUTH_EAST),
    bin_from=256, bin_to=16).run(ar[...,np.newaxis])
```

**Comment by Eve-ning** [comment]
Thanks for the issue raised, let me know if there's anything else 👍

**Comment by binit9** [comment]
A huge thanks for the prompt reply 👍 💯 

I got GLCM features of shape (44, 44, 3, 6), which was expected. (Pls let me know how to stop print the progress bar?)

So, I have 6 glcm features of shape (44, 44, 3) each.
But, the earlier skimage implementation, where I basically derived **one feature** as follows:

`contrast = greycoprops(glcm, 'contrast')[0, 0]`

How should I get that feature here? Is it `g[..., CONTRAST][0, 0, 0]` ? 
Does it make sense to use the first element of the co-matrix as a feature and discard others? (Sorry, I am new to texture analysis).

One more question I have: my CPU run took 50 ms on a single patch of size (50, 50), whereas **glcm_cupy** has just completed it in 65 ms on a (50, 50, 3) image - I believe, BGR image is not allowing us to get full effect to GPU speed-up. Your thoughts please.

Finally, is it possible to do **batch processing**? So to say, glcm on a batch of 300 patches --> (300, 50, 50, 3). I believe, that would significantly improve the run.

**Comment by APPGC** [comment]
Hello, really great work in implementing this. One question...:

I understand the image shrinks because of the effect of the sliding window on the edges. Wouldn't there be a way around that by padding the original image on its outside dimensions with artificial values (a number not used in the grayscale binning range - let's say 0, and then move the scale range by a digit (1-16), instead of (0-15), and from the GLCM, removing the rows with 0, before computing the haralick features?
